### ISSUE TITLE
How do you create a re-usable table component?

### ISSUE THREAD

**Issue by madhurgarg71** [siddharthkp/ama#10]
The problem right now is, if I want to create it completely reusable I need to consider table just for showing data. Something like this:

```javascript
<ReactTable data={tableData} config={tableConfig} />
````

If I consider above component and want to attach some event listener on some table column, e.g one column is `View (it's a button)`, I need to do it in the json data itself like this:
```javascript
const tableData = [{
      id: '1',
      name: 'Mike',
      age: 32,
      address: '10 Downing Street',
      '': getViewButton()
    }]
```

```javascript
 getViewButton() {
    return <button onClick={this.handleClick}>View</button>
 }
```
or I may attach a event listener to the table itself and use event bubbling technique.

This one feels generic and weird at the same time to me. Do you have any better idea? I have seen several react table components, but they are doing so many things. I want the API to be simple.

**Comment by siddharthkp** [comment]
@madhurgarg71 Whoops! Sorry, I completely missed this. Are you still looking for an answer 😅

**Comment by madhurgarg71** [comment]
@siddharthkp Yes, I mean if you can articulate some thoughts or do you have any suggestions, it would be great.

**Comment by madhurgarg71** [comment]
You can close this issue. I think I'm over generalizing stuff here and trying to make things complicated. It's unnecessary.
