### ISSUE TITLE
What are your thoughts on mobile app development?

### ISSUE THREAD

**Issue by vishalvrv9** [siddharthkp/ama#12]
***Disclaimer: I don't intend this question to be a comparison with web development. I know how every software system has its own upsides/downsides based on the use case/intent with which its idea came into being. Consider this a noob undergraduate who has just finished college seeking perspective of a senior developer/engineer who has been in the tech industry for a reasonably long period of time.*** 

I blame all of my social media feeds but the flutter UI framework has been creating a lot of stir (for me) everywhere. 
When a lot of the online product companies are moving towards PWAs (along with heavy JS usage), what is your take on flutter wrt the future?

[https://pchiusano.github.io/2016-02-25/tech-adoption.html](url)
Unrelated but this read made me ask this. 

I see that you've mentioned [here](https://github.com/siddharthkp/ama/issues/6) how learning a new language would slow you down. But for someone who's reasonably new to the tech industry (has only done internships/side projects; no full time jobs), do you consider learning mobile app development a step UP in terms of today's skillset demands?

**Comment by siddharthkp** [comment]
I see 2 questions here

> what is your take on flutter wrt the future?

Don't rely on your twitter feed to find the best tool, social media has a bias for promoting the new and flashy. That being said, it looks like an interesting solution. I'm not super interested in it because you need to learn Dart before jumping in /shrug

> for someone who's reasonably new to the tech industry (has only done internships/side projects; no full time jobs), do you consider learning mobile app development a step UP in terms of today's skillset demands?

Do you mind if I use the second question for https://twitter.com/siddharthkp/status/998797737075372032

**Comment by vishalvrv9** [comment]
>Do you mind if I use the second question for this video? (https://twitter.com/siddharthkp/status/998797737075372032)

Sure why not! 😄 *presses the bell icon on Youtube for updates*

**Comment by vishalvrv9** [comment]
>Don't rely on your twitter feed to find the best tool

Couldn't agree more. Honestly, I'm guilty of doing the same in my initial years of learning JS & I'm happy I'm past that phase. 
Just a clarification, the intent of the question was not to find the best tool but to understand the position and importance of a tool like flutter in today's software development ecosystem. As you mentioned, going with the adoption of Dart by google and stuff like creating a framework for app development (when things like ionic, stenciljs, react-native, etc already exist) made me wonder about google's motive wrt to the future.
