### ISSUE TITLE
Who do you work for currently?

### ISSUE THREAD

**Issue by spences10** [siddharthkp/ama#2]
tell me a bit about your previous roles too and what you'd like to be your next move.

**Comment by siddharthkp** [comment]
> Who do you work for currently?

I work for myself right now 😎  Learning javascript and experimenting with random side projects.

> previous roles

Until last month, I was working at [practo](https://practo.com) for a little over 4 years. That's the only employer I've had, and I learnt a lot over there.

> what you'd like to be your next move

I would love to work with folks smarter + nicer than me, building products for other developers. That's something that I find very gratifying 👼 

Thanks for asking!
