### ISSUE TITLE
Reading large codebase

### ISSUE THREAD

**Issue by m13m** [siddharthkp/ama#4]
How do you understand large code base? what tools do you use?

**Comment by siddharthkp** [comment]
That's a really good question!

Some tricks that have worked for me in the past for frontend codebases:

- First, understand what the application is supposed to do. Read the docs + talk to people. Understanding the context will help you make better guesses 😅
- Read the tests (if they exist, product requirements are a good proxy). Test cases tell a lot about the structure and interactions/use cases of the app.
- Try to learn how to navigate through the codebase. Find the entry points, go from there.
- Find a string from the UI, search it through your codebase to see which file is responsible for that part of the UI
- Delete code to see what breaks 😄 . This will help you visually assign parts of the application to code (this is the most underrated debugging method)
- Leave a lot of comments in the code. One at the top of the file to say what does this file do. One at the top of each function to explain when is this function used. Your co-workers will thank you

I don't know about any tools that are specially built for this, have you used one in the past?
