### ISSUE TITLE
What is your dev environment ?

### ISSUE THREAD

**Issue by asvny** [siddharthkp/ama#5]

**Comment by siddharthkp** [comment]
I use a MacBook Pro (13-inch, Mid 2014) with a  Vu 40 inch display + Sennheiser HD 419 Wired Headphone

These are the 3 apps I spent most of my time in:
1. [Google Chrome](https://www.google.com/chrome) browser
2. [Atom](https://atom.io) IDE
3. [Hyper](https://hyper.is) terminal

Apps that are always running in the background: 
1. [Vanilla](http://matthewpalmer.net/vanilla): Hide menu bar icons on your Mac.
2. [RescueTime](rescuetime.com): Track where you spend your time
3. [Memory Clean 2](https://fiplab.com/apps/memory-clean-for-mac): Frees up RAM when needed 

Occasional apps that are super useful
1. [Licecap](https://www.cockos.com/licecap): Screen recording to GIF
2. [notella](https://siddharthkp.github.io/notella): No fluff notes app
3. [Insomnia](https://insomnia.rest): REST client for working with APIs
4. iTunes 🎵

Editor stuff:
Theme: [One dark theme](https://atom.io/themes/one-dark-ui) + [80s pastel syntax](https://atom.io/themes/80s-pastel-syntax) + [Source Code Pro font](https://atom.io/packages/fonts)
Crucial packages: [prettier-atom](https://atom.io/packages/prettier-atom), [markdown preview plus](https://atom.io/packages/markdown-preview-plus), [atom-import cost](https://atom.io/packages/atom-import-cost)

Let me know if you want to know something specific 😄

**Comment by asvny** [comment]
Too much detail !
