### ISSUE TITLE
which programming language would you like to learn ?

### ISSUE THREAD

**Issue by asvny** [siddharthkp/ama#6]

**Comment by siddharthkp** [comment]
Oh man! This one is tricky.

There's mainstream backend languages on my list: Python, Ruby
and compile to JS languages: Typescript, Reason, Elm

But, honestly, I don't think I'll be learning them anytime soon. I do all of my full stack work in Javascript these days and feel super productive with it.

Learning a new language needs you to slow down for a while, I don't think I have the patience for that right now 😅
