### ISSUE TITLE
Any websites or threads which you regularly check to keep yourself updated.

### ISSUE THREAD

**Issue by shreyas-a** [siddharthkp/ama#8]

**Comment by siddharthkp** [comment]
In addition to newsletters (https://github.com/siddharthkp/ama/issues/7), I spent way too much time on twitter!

I have a hard time reading long articles 😅, so I prefer watching youtube instead (conference talks, developer channels, etc.)

I see myself visiting [MDN](https://developer.mozilla.org/en-US/docs/Web) and [dribbble](dribbble.com) a lot too.

Happy to answer any specific questions 😄
