### ISSUE TITLE
What Atom packages do you have installed?

### ISSUE THREAD

**Issue by AdrianVovk** [siddharthkp/ama#9]

**Comment by siddharthkp** [comment]
I'm really bad when it comes to customising my editor, but here's what I have going on:

1. [prettier-atom](https://atom.io/packages/prettier-atom): can't live without it
1. [pigments](https://atom.io/packages/pigments): shows colors for hex values in code
1. [fonts](https://atom.io/packages/fonts): gotta have my Source Code Pro
1. [atom-import-cost](https://atom.io/packages/atom-import-cost): an atom port of [import-cost](https://github.com/wix/import-cost)

Suggestions are welcome 😄
